server:
  port: 8060
  servlet:
    context-path: /hoomi

spring:
  application:
    name: hoomi-management-app
  main:
    web-application-type: servlet
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/hoomi-db?createDatabaseIfNotExist=true}
    username: ${DATABASE_USERNAME:hoomi-user}
    password: ${DATABASE_PASSWORD:hoomi-password}
info:
  app:
    name: Hoomi Management
    version: @project.version@

#firabase
firebase:
  key: ${FIREBASE_KEY_PATH:./hoomi-firebase-firebase-adminsdk.json}
#security
jwt:
  secret: ${JWT_SECRET:secret}
  ttl: ${JWT_TTL:5} #min

#actuator
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: info, health, logfile, httptrace, loggers
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: hoomi-management-logs/current.log
  trace:
    http:
      include: PRINCIPAL, REQUEST_HEADERS, RESPONSE_HEADERS, TIME_TAKEN
